# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pessoa', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoas.Pessoa', verbose_name='Usuário')),
                ('email', models.EmailField(max_length=80, verbose_name='E-mail')),
                ('telefone_1', models.CharField(blank=True, max_length=11, verbose_name='Telefone Residencial')),
                ('telefone_2', models.CharField(blank=True, max_length=11, verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
            bases=('pessoas.pessoa',),
        ),
    ]
