# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.ManyToManyField(null=True, to='especialidades.Especialidade'),
        ),
    ]
