# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_auto_20160811_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.ManyToManyField(to='especialidades.Especialidade'),
        ),
    ]
