# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_auto_20160816_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nomeArea',
            field=models.CharField(max_length=80, verbose_name='Profissão'),
        ),
    ]
