# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEspecialidade', models.CharField(max_length=80, verbose_name='Especialidade')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Area')),
            ],
            options={
                'ordering': ['nomeEspecialidade'],
            },
        ),
    ]
