# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0004_auto_20160708_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
    ]
