# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidade',
            options={'ordering': ['nomeEspecialidade']},
        ),
        migrations.RenameField(
            model_name='especialidade',
            old_name='especialidade',
            new_name='nomeEspecialidade',
        ),
        migrations.AddField(
            model_name='especialidade',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='areas.Area'),
            preserve_default=False,
        ),
    ]
