# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.Pessoa')),
                ('email', models.CharField(max_length=80, verbose_name='Email')),
                ('senha', models.CharField(max_length=80, verbose_name='Senha')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'verbose_name': 'Usuário',
            },
            bases=('pessoas.pessoa',),
        ),
    ]
