# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.CharField(max_length=100, verbose_name='Clínica / Hospital')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('cep', models.IntegerField(max_length=8, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=80, verbose_name='Cidade')),
            ],
            options={
                'ordering': ['estabelecimento'],
            },
        ),
    ]
