# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='ddd',
            field=models.CharField(default='089', max_length=3, verbose_name='DDD'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='telefone_1',
            field=models.CharField(blank=True, max_length=9, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='cep',
            field=models.IntegerField(blank=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='cidade',
            field=models.CharField(default='Picos', max_length=80, verbose_name='Cidade'),
        ),
    ]
