# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0002_auto_20160629_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.Cidade'),
        ),
    ]
