# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0002_auto_20160629_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='telefone_2',
            field=models.CharField(blank=True, max_length=9, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='telefone_1',
            field=models.CharField(max_length=8, verbose_name='Telefone Comercial'),
        ),
    ]
