# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propagandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propaganda',
            name='urlImgPropaganda',
            field=models.CharField(max_length=80, verbose_name='Numero'),
        ),
    ]
