# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propagandas', '0003_auto_20160704_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propaganda',
            old_name='proficional',
            new_name='profissional',
        ),
    ]
