# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.CharField(default='Médico', max_length=80, verbose_name='Profissão')),
                ('crm', models.CharField(max_length=10, verbose_name='CRM')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='pessoas.Pessoa')),
            ],
        ),
    ]
