# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='especialidade',
            field=models.ManyToManyField(to='especialidades.Especialidade'),
        ),
    ]
