# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='urlImgProficional',
        ),
        migrations.AddField(
            model_name='profissional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/images', verbose_name='Imagem'),
        ),
    ]
