# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_auto_20160704_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='image',
            new_name='urlImgProfissional',
        ),
    ]
