# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_profissional_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='pessoas.Pessoa', verbose_name='Nome'),
        ),
    ]
