# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_auto_20160627_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='pessoas.Pessoa', verbose_name='Dados Pessoais'),
        ),
    ]
