# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0004_auto_20160627_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['pessoa'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterField(
            model_name='profissional',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='pessoas.Pessoa', verbose_name='Profissional'),
        ),
    ]
