# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
        ('profissionais', '0005_auto_20160628_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='estabelecimento',
            field=models.ManyToManyField(to='estabelecimentos.Estabelecimento', verbose_name='Locais de Atendimento'),
        ),
    ]
